name: unicons
description: un test unicon
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http:
  sqflite:
  path:
  ical_parser:
  background_fetch:
  flutter_local_notifications:

  cupertino_icons: ^1.0.2

  flutter_html: ^2.1.1
  flutter_week_view: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - res/
  fonts:
    - family: aAnggota
      fonts:
        - asset: res/font/aAnggota.ttf
    - family: LinLiber
      fonts:
        - asset: res/font/LinLibertine_R.ttf
        - asset: res/font/LinLibertine_RB.ttf
          style: italic
        - asset: res/font/LinLibertine_RBI.ttf
          style: italic
          weight: 700
        - asset: res/font/LinLibertine_RI.ttf
          weight: 700

