name: unicon
description: Unicon20 companion application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# need to specify versions ?
# security checks can be done before each release build
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:

  provider:

  http:
  http_retry:

  sqflite:
  path:

  ical_parser:
    git: https://github.com/lpoujade/ical-parser

  background_fetch:
  flutter_local_notifications:

  rflutter_alert:
  auto_size_text:
  fluttertoast:
  html_unescape:
  flutter_html: 
  url_launcher:

  flutter_week_view:
  cached_network_image:

  universe:
    git: https://github.com/lpoujade/universe
  flutter_cached_pdfview: ^0.4.1

dev_dependencies:
  dartdoc:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter

  flutter_lints:


flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/app_icon_no_alpha.png"
  image_path_android: "assets/app_icon.png"
  adaptive_icon_foreground: "assets/foreground-432x432.png"
  adaptive_icon_background: "assets/background.png"

flutter:
  uses-material-design: true
  assets:
    - res/
    - assets/
  fonts:
    - family: Tahoma
      fonts:
        - asset: res/font/tahoma.ttf
    - family: Futura
      fonts:
        - asset: res/font/futura/futura.ttf
        - asset: res/font/futura/futura-bold.ttf
          weight: 700
